### PR TITLE
Adding unit test support

### PR DESCRIPTION
**Pull request by brauliodiez**
Added unit test support.

To run the test
- Is it needed to have already installed karma
- Run npm install
- Run bower install
- Navigate to the 'test' folder an execute from the command prompt _karma start_

All tests passing but Kosovo (country code not existing)

### CODE REVIEW

**Comment by chiefjester** [comment]
@juvenpajares heads up.

**Comment by brauliodiez** [comment]
Hello @juvenpajares, should I proceed with the merge of this branch? Cheers

**Comment by dane206** [comment]
@brauliodiez please do not merge this branch until @juvenpajares or @deezahyn approves. thanks!

**Comment by juvenpajares** [comment]
@brauliodiez this unit test seems fine on my end. here's my results, Chrome 43.0.2357 (Mac OS X 10.10.3): Executed 164 of 164 SUCCESS (1.079 secs / 1.057 secs).

**Pull request merged**
